# Generated by Django 5.0 on 2023-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='display_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='display_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
