# Generated by Django 5.0 on 2023-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_menucategory_display_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='display_picture',
            field=models.ImageField(upload_to='menu-categories'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='display_picture',
            field=models.ImageField(upload_to='menu-items'),
        ),
    ]
