# Generated by Django 4.2.1 on 2023-12-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_events_menuitem_is_featured_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
