# Generated by Django 4.2.1 on 2024-01-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reservation_created_at_reservation_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
